services:
  # Notification server
  api:
    build: .
    container_name: notification-api
    env_file:
      - .env.sample
    ports:
      - "8080:8080"
    environment:
      - DB_URL=postgres://amx:amx@db:5432/notification?sslmode=disable
    depends_on:
      db:
        condition: service_healthy

  # PG DB
  db:
    image: postgres:16
    container_name: notification-postgres
    environment:
      POSTGRES_USER: amx
      POSTGRES_PASSWORD: amx
      POSTGRES_DB: notification
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U amx -d notification"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
